// AUTO-GENERATED by: npm run db:types
// Do NOT edit manually. Run `npm run db:types` after schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; email: string; full_name: string | null; timezone: string; created_at: string; updated_at: string }
        Insert: { id: string; email: string; full_name?: string | null; timezone?: string; created_at?: string; updated_at?: string }
        Update: { id?: string; email?: string; full_name?: string | null; timezone?: string; updated_at?: string }
      }
      habits: {
        Row: { id: string; user_id: string; goal_id: string | null; name: string; description: string | null; frequency: Database['public']['Enums']['habit_frequency']; custom_days: boolean[] | null; target_value: number; unit: string; deleted_at: string | null; created_at: string; updated_at: string }
        Insert: { id?: string; user_id: string; goal_id?: string | null; name: string; description?: string | null; frequency?: Database['public']['Enums']['habit_frequency']; custom_days?: boolean[] | null; target_value?: number; unit?: string; deleted_at?: string | null; created_at?: string; updated_at?: string }
        Update: { goal_id?: string | null; name?: string; description?: string | null; frequency?: Database['public']['Enums']['habit_frequency']; custom_days?: boolean[] | null; target_value?: number; unit?: string; deleted_at?: string | null; updated_at?: string }
      }
      habit_logs: {
        Row: { id: string; habit_id: string; user_id: string; logged_date: string; completed_value: number; note: string | null; created_at: string; updated_at: string }
        Insert: { id?: string; habit_id: string; user_id: string; logged_date: string; completed_value?: number; note?: string | null; created_at?: string; updated_at?: string }
        Update: { completed_value?: number; note?: string | null; updated_at?: string }
      }
      tasks: {
        Row: { id: string; user_id: string; goal_id: string | null; title: string; description: string | null; status: Database['public']['Enums']['task_status']; priority: Database['public']['Enums']['task_priority']; due_date: string | null; completed_at: string | null; created_at: string; updated_at: string }
        Insert: { id?: string; user_id: string; goal_id?: string | null; title: string; description?: string | null; status?: Database['public']['Enums']['task_status']; priority?: Database['public']['Enums']['task_priority']; due_date?: string | null; completed_at?: string | null; created_at?: string; updated_at?: string }
        Update: { goal_id?: string | null; title?: string; description?: string | null; status?: Database['public']['Enums']['task_status']; priority?: Database['public']['Enums']['task_priority']; due_date?: string | null; completed_at?: string | null; updated_at?: string }
      }
      goals: {
        Row: { id: string; user_id: string; title: string; description: string | null; status: Database['public']['Enums']['goal_status']; target_date: string; deleted_at: string | null; created_at: string; updated_at: string }
        Insert: { id?: string; user_id: string; title: string; description?: string | null; status?: Database['public']['Enums']['goal_status']; target_date: string; deleted_at?: string | null; created_at?: string; updated_at?: string }
        Update: { title?: string; description?: string | null; status?: Database['public']['Enums']['goal_status']; target_date?: string; deleted_at?: string | null; updated_at?: string }
      }
    }
    Enums: {
      habit_frequency: 'daily' | 'weekdays' | 'weekends' | 'custom'
      goal_status:     'active' | 'completed' | 'abandoned'
      task_status:     'todo' | 'in_progress' | 'done'
      task_priority:   'low' | 'medium' | 'high'
    }
  }
}
